version: '2'
services:
  gocd.master:
    build: .
    volumes:
      - ./data/master/var/lib/go-server:/var/lib/go-server
      - ./data/master/etc/go:/etc/go

  gocd.agent:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
